### ISSUE TITLE
microphone support

### ISSUE THREAD

**Issue by julianborghuis** [kimmknight/remoteapptool#16]
Is it possible to add microphone support?

**Comment by MrBrianGale** [comment]
This feature could be added.  I should have time to start working on this feature sometime this week. Something to note though - microphone over RDP is not advised as it is higher bandwidth and can have audio delays and stutter.
When I add this feature, it will have a popup box to let you know that turning it on is not advised.
I will also add an option to control how audio is processed.  It can either play the audio at the local machine, the remote machine or not at all.  When you select to use the microphone, I will have it auto-select to have audio on the local machine as that makes the most sense.
By default, these will both be disabled as pulling audio across also results in higher bandwidth and can cause audio delays and stutter.

Since I am going to implement this, are there other features you'd like me to add?  Here is a list of features that can be included:
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/rdp-files

**Comment by julianborghuis** [comment]
Is that popup able to disable?
Because i want that popup dont,

maybe, add a permission system to give some programs access to a specified folder?

If you have discord you can add me Julian#8969

**Comment by MrBrianGale** [comment]
My reason for bringing up the popup is that some users may not understand the impact of having that turned on and I'd like to avoid issues being created due to stuttering or crackling audio from the mic or speakers when using this tool as it is a limitation of RDP.
As this tool is used by a lot of people, some without knowledge of RDP limitations, having that option enabled and available to everyone may result in less than ideal RDP experiences.

The other option I can think of doing is having a separate window for "advanced options" that you need to go to in order to allow for microphone settings and speaker settings and this would give me room on the form to put the warnings.

Also, just so I am 100% clear about what you are asking, is this a feature you want added to the RDP file export (and potentially the MSI file creation) OR is this something you want added to the remoteapp itself? Adding it to the RDP file is possible; adding it to the remoteapp itself is not.

**Comment by julianborghuis** [comment]
rdp file

**Comment by julianborghuis** [comment]
The other option I can think of doing is having a separate window for "advanced options" that you need to go to in order to allow for microphone settings and speaker settings and this would give me room on the form to put the warnings.

thats super!

**Comment by MrBrianGale** [comment]
Ok, then adding it in is pretty easy.
I can add the advanced options window which can have multiple "advanced" options that most users will not use and I can provide mouseover help text on them.
I'll likely put text at the top with something like:
WARNING - turning these options on may cause increase in bandwidth or loss of quality.  Audio options may cause stuttering and delays.  Use these options at your own risk.  Mouse-over an option to see the potential issues.

Then have mouseovers for the various options to indicate potential issues.  Could also have a big empty text block where you can add your own options too.  I'd like to avoid that as it may open up a huge can of worms towards issues of features not supported only to find out a user made a typo.

If things go as planned, I should have something ready to test on my fork of this project by the end of the week.

**Comment by julianborghuis** [comment]
Cool but was hoping today but end this week is ok

**Comment by MrBrianGale** [comment]
Until this gets released, you can modify the .RDP file (as long as you didn't sign it) and add in microphone support using the link I mentioned above.

**Comment by MrBrianGale** [comment]
Got this implemented faster than I expected.
It can be found on my fork of the project at:
https://github.com/MrBrianGale/remoteapptool/releases/tag/AdvancedOptions

My fork is built in debug mode so error messages (if any come up) will be unfriendly error messages but useful to developers.  It also doesn't have compiler optimizations, but I doubt you would notice anything with that except possibly slightly higher memory usage.
Once my other pull request gets pulled into the master branch, I will make a new one for this issue and it may end up in the live tool.  OR kimmknight may decide they don't like my changes and it never hits the main release.
This is afterall kimmknight's work; I am just helping with it as it is an interesting project and I have the skills and time to add features.

**Comment by julianborghuis** [comment]
https://gyazo.com/6b7d4ebaf367d896d8ef8b5d69a0eadf

**Comment by julianborghuis** [comment]
getting that errpr..https://gyazo.com/c36693e946105daa0e44997e392c4a6f

**Comment by MrBrianGale** [comment]
This likely isn't an issue with the remoteapp but an issue with how the browser asks for audio.  I would try it with a tool that has a known audio request at application startup rather than an application that has a delayed request for microphone.  Failing that, there may be some configuration in your browser that needs to be set up.
I tested it with this tool:
https://sourceforge.net/projects/audmes/c
going from PC A to PC B (not real PC names, just indicating I wasn't running it locally) and I was able to select the audio devices and hear and see things happening so I am fairly confident it works.
Looking at my chrome settings, which is mostly default settings, the microphone is disabled by default.  My guess is that you did not enable the microphone in your browser settings OR didn't allow it for that site.
A RemoteApp session is not the same thing as a remote desktop session and as such some settings you set in Remote Desktop MAY not be set the same in a RemoteApp.

**Comment by MrBrianGale** [comment]
Did the microphone work after adjusting browser settings?
I should have a little bit of time to test this today as well...

**Comment by MrBrianGale** [comment]
I just tested this in Chrome using remoteapps and it seemed to work fine for me once I allowed the webpage to use my microphone.
Thinking either:
A - you didn't change the advanced setting for the Mic from "Disabled" to "Enabled"
B - you didn't enable the microphone for the webpage when it requested it
C - you didn't turn microphone settings on in the browser settings.

**Comment by julianborghuis** [comment]
Another thing.

I cant create an msi installer...


`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.IOException: The process cannot access the file 'C:\Users\Administrator\AppData\Local\Temp\1\Google Chrome.rdp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveFile(CopyOrMove operation, String sourceFileName, String destinationFileName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at RDP2MSIlib.RDP.CreateMSI(String DestinationPath)
   at RemoteApp_Tool.RemoteAppCreateClientConnection.CreateButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
RemoteApp Tool
    Assembly Version: 5.3.0.0
    Win32 Version: 5.3.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RemoteApp%20Tool/RemoteApp%20Tool.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
RemoteAppLib
    Assembly Version: 1.0.0.1
    Win32 Version: 1.0.0.1
    CodeBase: file:///C:/Program%20Files%20(x86)/RemoteApp%20Tool/RemoteAppLib.DLL
----------------------------------------
IconLib
    Assembly Version: 0.73.0.0
    Win32 Version: 0.73.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RemoteApp%20Tool/IconLib.DLL
----------------------------------------
RDP2MSIlib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RemoteApp%20Tool/RDP2MSIlib.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
RDPFileLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RemoteApp%20Tool/RDPFileLib.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3282.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


`

**Comment by MrBrianGale** [comment]
Are you making the MSI using the official release OR my debug release?

**Comment by MrBrianGale** [comment]
Also, did you get any popup about the file being locked OR just straight to the error message?

**Comment by MrBrianGale** [comment]
Never mind... answered my own question.  the MSI installer bug is a known issue in the official release.  Please use my release to provide more debugging information so we can capture and correct the locking issue.

**Comment by MrBrianGale** [comment]
Check out:
https://github.com/MrBrianGale/remoteapptool/releases
For an updated version of the release with Audio IN and Audio OUT options  added.
Also, can I get you to try the above version for the MSI installer options?  It likely won't be resolved in this release, but will hopefully give better error messages.

**Comment by julianborghuis** [comment]
https://hastebin.com/subofixidu.sql

**Comment by MrBrianGale** [comment]
Did you get any pop-ups telling you that file may be locked prior to the error message coming up?

**Comment by julianborghuis** [comment]
It was saying that the program already in use was but this is with all the programs

**Comment by MrBrianGale** [comment]
Did it give you a popup saying "The file chrome.rdp is currently locked.  Lock information: "?  If so, could you post that screenshot?   If the file is locked by something, then the tool cannot make the MSI file.  Knowing what is locking it AND unlocking the file is required for things to continue.
Although, the popup should not allow the code to continue until the file is unlocked OR you ignore the file  lock and tell it to continue.  The next popup that comes up provides incorrect information and I need to fix that... it tells you the file will not be deleted, but it isn't a file deletion, it is a file copy.  And the file copy is required, so it should stop processing if you do not try again.  I'll need to update that.

**Comment by julianborghuis** [comment]
I can click continue but the file is not saved then and no error that the file is saved then .
https://gyazo.com/723e4b9d557058c3628a8b6b3f8c8500

**Comment by MrBrianGale** [comment]
Ok... that is the only popup that comes up (big ugly error message), no friendly one that syas "The file Internet Explorer.rpd is currently locked"?  That sucks.  I'll need to do more investigating on that.  I am not able to reproduce that problem which makes it incredibly difficult to fix.  I thought I had some code in there to bring up a friendly error instead of the ugly error but apparently it isn't working...

**Comment by MrBrianGale** [comment]
I think I fixed the issue.  Can I get you to try out this release:
https://github.com/MrBrianGale/remoteapptool/releases/tag/Issue%233

**Comment by julianborghuis** [comment]
https://gyazo.com/5ae656b2f379b37594fb991c31830343

**Comment by MrBrianGale** [comment]
Just wanted to confirm - that screenshot is from the latest link I provided?  The stats I see show that nobody has downloaded that version.
It could be the download stats are out of date though.
If it is the one with the tag "Issue#3", then I can work on this a bit more and see what I can figure out...  That error shouldn't happen anymore...

**Comment by julianborghuis** [comment]
yes from your latest release 
https://github.com/MrBrianGale/remoteapptool/releases/tag/Issue%233

**Comment by MrBrianGale** [comment]
Well,shoot... Ok... I will play with that some more and see what I can figure out.
I am not sure why that version is still throwing that error... The only thought I have is that it isn't the destination file that is giving the error but the source file... 

Next build will have some extra pop-ups come up so I can try to figure out what is happening.  I will remove them once we figure this bug out.
As a thought - do you get the same error message building the MSI in the official build or is it just my builds causing that error?

**Comment by julianborghuis** [comment]
It is also in the original source

**Comment by MrBrianGale** [comment]
I am glad to hear I didn't create a new bug.
I will work on getting this bug corrected, but likely won't have anything ready to test before Monday at the earliest.

Does the Microphone stuff work?

**Comment by MrBrianGale** [comment]
Still working on this... not sure where the problem is so it is hard to fix it.  I know the line of code causing the problem, but I cannot figure out why (yet) it is being locked in some cases and am not able to reproduce the problem.  So my next step with this may just be to make it a friendly error message or I may need to do some force-locking of the file on my end to see what causes the lock.  Based on the most recent screenshot you sent in, I am thinking it is a lock on the SOURCE file not the DESTINATION file which is weird and something I never thought to check when working on that portion of the code.

**Comment by MrBrianGale** [comment]
Did some work and have better handling now of the file locking which will hopefully fix the issue.  Can I get you to test out this version:
https://github.com/MrBrianGale/remoteapptool/releases/tag/AdvancedOptions%7C_RDPOnly

Also, could you let me know if the microphone settings are working for you?  they worked for me, but just because it works for me doesn't mean the problem is fixed.

**Comment by sashaqwert** [comment]
I was interested in microphone support but was waiting for a stable version

**Comment by MrBrianGale** [comment]
It is an interesting feature and was easy to implement, but if I am the only one testing it, I am not comfortable with it going live.  I MAY have introduced some bugs that I was not able to trigger with my testing so I want it tested outside of just me.  There also was not too much interest in the feature as only one person requested it and tested it.
Basically, if nobody tests the "test" builds, those features will not make it into stable.

**Comment by Neustradamus** [comment]
Have you progressed on this microphone support?

**Comment by MrBrianGale** [comment]
I am not sure if this got into the most recent build or not. I didn't not push my changes up as there was no interest in the feature and nobody apart from me was willing to test it. No testing means I am not comfortable pushing it live, so did not push those changes live.
BUT version 6 had a major overhaul on the app by the maintainer. I would say give that version a shot and it MAY work for you.

**Comment by pergolafabio** [comment]
> I am not sure if this got into the most recent build or not. I didn't not push my changes up as there was no interest in the feature and nobody apart from me was willing to test it. No testing means I am not comfortable pushing it live, so did not push those changes live. BUT version 6 had a major overhaul on the app by the maintainer. I would say give that version a shot and it MAY work for you.

Hi, just wondering, how can an microphone be used

I have on my host an SIP application, but my bluetooth headset is connected to my local PC , is there a way i can connect it to each other? cause on my host there is no input device .... 

thnx

**Comment by kimmknight** [comment]
> Hi, just wondering, how can an microphone be used

I think this should do it:

![Image](https://github.com/user-attachments/assets/d904bb97-d0f2-4c6f-bfe6-0ebd304cb55a)

**Comment by pergolafabio** [comment]
yeah, already tried and working, had to add some tweaks to have better audio support, seems audio over RDP was compressed

**Comment by pergolafabio** [comment]
this one:

`audioqualitymode:i:2`

and on host this one:

```
Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Device and Resource Redirection

Set the policy Limit audio playback quality to enabled and high and then reboot.
```
